FROM node:20

RUN npm install -g firebase-tools

WORKDIR /app

COPY firebase.json .firebaserc ./
COPY functions/ functions/

RUN cd functions && npm install

EXPOSE 4000 5001

CMD ["firebase", "emulators:start", "--only", "functions", "--project", "butterfly-memorial"]
